- name: Terraform Init
  working-directory: environments/preprod
  run: terraform init

- name: Terraform Validate
  working-directory: environments/preprod
  run: terraform validate

- name: Terraform Plan
  working-directory: environments/preprod
  run: terraform plan
